spring:
  application:
    name: kotlinapi
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

logging:
  level:
    o.apache.tomcat.util.http.parser.Cookie: DEBUG